baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "ananke"

[permalinks]
  posts = "/:slug/"

[frontmatter]
  date = ["date", "publishDate", ":filename", "lastmod"]

