virsion: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    environment:
      - TARGET_DIRS: "news|press-release"
    steps:
      - checkout
      - run:
          name: Check title and summary field
          command: |
            files=$(git diff --name-only --diff-filter=ACMR origin/master..HEAD -- '*.md' | grep -P "(^|/)(${TARGET_DIRS})/")
            [ -z "$files" ] && exit 0
            for file in $files ; do
              if [ -z "$( cat "$file" | grep -oPz '\-{3}[\s\S]+?title:[\s\S]+?\-{3}' )" ] || [ -z "$(cat "$file" | grep -oPz '\-{3}[\s\S]+?summary:[\s\S]+?\-{3}')" ] ; then
                echo 'Error: Either title or summary field is not satisfied!'
                exit 1
              fi
            done

